language: python
sudo: false

matrix:
  include:
    - python: "2.7"
      env: DEPS="numpy=1.9 scipy=0.15 astropy=1.0"
    - python: "3.4"
      env: DEPS="numpy=1.9 scipy=0.15 astropy=1.0"
    - python: "2.7"
      env: DEPS="numpy=1.9 scipy=0.15 astropy=1.0" COVERAGE=true

cache:
  directories:
    - $HOME/.pip-cache/
    - /home/travis/virtualenv/python2.7

install:
  # See:
  # https://groups.google.com/a/continuum.io/forum/#!topic/conda/RSFENqovnro
  # - conda update --yes --no-deps conda
  # OK, this used to *fix* the build, but now it *breaks* the build.
  # If you're reading this, good luck out there. I'm not sure what to tell you.
  - conda update --yes conda
  - conda create -n testenv --yes $DEPS pip pytest setuptools Cython six>=1.7 pyyaml python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - pip install pytest-benchmark
  - pip install -e git+git://github.com/guaix-ucm/numina.git#egg=numina
  - if [[ $COVERAGE == true ]]; then pip install coveralls; fi
  - pip install photutils --download-cache $HOME/.pip-cache
  - pip install matplotlib six scikit-image>=0.10 --download-cache $HOME/.pip-cache
  # Build in place so we can run tests
  - python setup.py build_ext --inplace

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

script: 
  - py.test emirdrp
  - if [[ $COVERAGE == true ]]; then coverage run --source emirdrp -m py.test; fi

after_success:
  - if [[ $COVERAGE == true ]]; then coveralls; fi
