name: EMIR
configurations:
  values:
  - 225fcaf2-7f6f-49cc-972a-70fd0aee8e96
datamodel: emirdrp.datamodel.EmirDataModel
modes:
- description: A recipe that always fails
  key: fail
  name: Fail
  summary: A recipe that always fails
- description: Recipe to process bias images
  key: IMAGE_BIAS
  name: Bias Image
  summary: Recipe to process bias images
- description: Lines and mode lines
  key: IMAGE_DARK
  name: Dark current Image
  summary: Summary of Dark current Image
- description: Lines and mode lines
  key: IMAGE_FLAT
  name: Intensity Flat-Field
  summary: Summary of Intensity Flat-Field
- description: Lines and mode lines
  key: STARE_IMAGE
  name: Stare Image
  summary: Summary of Stare Image
- description: Lines and mode lines
  key: NODDED_BEAM_SWITCHED_IMAGE
  name: Nodded/Beam-switched images
  summary: Summary of Nodded/Beam-switched images
- description: Lines and mode lines
  key: DITHERED_IMAGE
  name: Dithered images
  summary: Summary of Dithered images
- description: Lines and mode lines
  key: MICRODITHERED_IMAGE
  name: Micro-dithered images
  summary: Summary of Micro-dithered images
- description: Lines and mode lines
  key: MOSAICED_IMAGE
  name: Mosaiced images
  summary: Summary of Mosaiced images
- description: Lines and mode lines
  key: gain_mode1
  name: Gain Mode1
  summary: Summary of GainMode1
- description: Lines and mode lines
  key: cosmetics
  name: Cosmetics
  summary: Summary of GainMode1
- description: Lines and mode lines
  key: dark_current
  name: DarkCurrent
  recipe: emirdrp.recipes.aiv.DarkCurrentRecipe
  summary: Summary of DarkCurrent
- description: A Simple Bias recipe for testing
  key: simple_bias
  name: Simple Bias
  summary: Summary of Simple Bias
- description: Does nothing
  key: TEST0
  name: Test success
  summary: Summary
- description: Bias correct
  key: TEST1
  name: Test Bias Correct
  summary: Summary
- description: Dark correct
  key: TEST2
  name: Test Dark Correct
  summary: Summary
- description: Flat correct
  key: TEST3
  name: Test Flat Correct
  summary: Summary
- description: Sky subtracction
  key: TEST5
  name: Test sky subtraction
  summary: Summary
- description: Flat correct
  key: TEST6
  name: Test pinhole extraction
  summary: Summary
- description: Simple sky background
  key: IMAGE_SKY
  name: Test pinhole extraction
  summary: Summary
- description: Slit extraction in pinhole mask
  key: TEST7
  name: Test slit extraction
  summary: Summary
- key: TEST8
  name: Multiflat
  summary: Multiflat
  description: Simultaneous flat in several bands
- description: Wavelength calibration from arc
  key: ARC_CALIBRATION
  name: Wavelength calibration
- description: Extracts spectra of the slits in the AIV mask
  key: TEST9
  name: Slit-mask spectra extraction
  summary: Summary
- description: Extracts spectra of the slits in the AIV mask
  key: TEST9
  name: Slit-mask spectra extraction
  summary: Summary
- description: Positions of the CSU bars
  key: TEST10
  name: Bar detection
  summary: Positions of the CSU bars
- description: Extraction of spectra
  key: TEST11
  name: TEST11
  summary: Extraction of spectra
- description: Alternative positions of the CSU bars
  key: TEST12
  name: TEST12
  summary: Positions of CSU bars
- key: TEST13
  name: TEST13
  summary: Mask Check
  description: Acquire and check mask
- description: Lines and mode lines
  key: FULL_DITHERED_IMAGE
  name: Dithered images
  summary: Summary of Dithered images
- key: STARE_SPECTRA
  name: Stare Spectra
  summary: Stare Spectra
  description: Stare Spectra
- key: LS_ABBA
  name: Long Slit ABBA
  summary: Spectroscopy ABBA
  description: Spectroscopy ABBA
- key: COMBINED_ABBA
  name: Combined individual Long Slit ABBA
  summary: Combined individual Long Slit ABBA
  description: Combined individual Long Slit ABBA
- key: SPEC_SKY
  name: SPEC_SKY
  summary: SPEC_SKY
  description: SPEC_SKY
- key: SPECTRAL_FLAT
  name: SPECTRAL FLAT mode
  summary: SPECTRAL FLAT mode
  description: SPECTRAL FLAT mode
pipelines:
  default:
    products:
      MasterBias: emirdrp.products.MasterBias
      MasterBadPixelMask: emirdrp.products.MasterBadPixelMask
      MasterDark: emirdrp.products.MasterDark
      MasterIntensityFlat: emirdrp.products.MasterIntensityFlat
      MasterSpectralFlat: emirdrp.products.MasterSpectralFlat
    provides:
      - name: MasterBadPixelMask
        mode: cosmetics
        field: biasframe
      - name: MasterBias
        mode: IMAGE_BIAS
        field: biasframe
      - name: MasterDark
        mode: IMAGE_DARK
        field: darkframe
      - name: MasterIntensityFlat
        mode: IMAGE_FLAT
        field: flatframe
      - name: MasterSpectralFlat
        mode: SPECTRAL_FLAT
        field: flatframe
      - name: MasterSky
        mode: IMAGE_SKY
        field: skyframe
      - name: SkySpectrum
        mode: SPEC_SKY
        field: skyspec
    recipes:
      IMAGE_BIAS: emirdrp.recipes.auxiliary.BiasRecipe
      IMAGE_DARK: emirdrp.recipes.auxiliary.DarkRecipe
      IMAGE_FLAT: emirdrp.recipes.auxiliary.IntensityFlatRecipe
      IMAGE_SKY: emirdrp.recipes.auxiliary.DitherSkyRecipe
      SPECTRAL_FLAT: emirdrp.recipes.auxiliary.SpectralFlatRecipe
      DITHERED_IMAGE: emirdrp.recipes.image.join.JoinDitheredImagesRecipe
      FULL_DITHERED_IMAGE: emirdrp.recipes.image.join.FullDitheredImagesRecipe
      MICRODITHERED_IMAGE: emirdrp.recipes.image.micro.MicroditheredImageRecipe
      MOSAICED_IMAGE: emirdrp.recipes.image.mosaic.MosaicRecipe
      NODDED_BEAM_SWITCHED_IMAGE: emirdrp.recipes.image.nodded.NBImageRecipe
      STARE_IMAGE: emirdrp.recipes.image.stare.StareImageBaseRecipe
      fail: numina.core.utils.AlwaysFailRecipe
      gain_mode1: emirdrp.recipes.engineering.GainRecipe1
      cosmetics: emirdrp.recipes.engineering.CosmeticsRecipe
      simple_bias: emirdrp.recipes.aiv.SimpleBiasRecipe
      TEST0: numina.core.utils.AlwaysSuccessRecipe
      TEST1: emirdrp.recipes.aiv.TestBiasCorrectRecipe
      TEST2: emirdrp.recipes.aiv.TestDarkCorrectRecipe
      TEST3: emirdrp.recipes.aiv.TestFlatCorrectRecipe
      TEST4: emirdrp.recipes.aiv.TestFlatCorrectRecipe
      TEST5: emirdrp.recipes.aiv.sky.TestSkyCorrectRecipe
      TEST6: emirdrp.recipes.aiv.pointsources.TestPointSourceRecipe
      TEST7: emirdrp.recipes.aiv.slits.TestSlitDetectionRecipe
      TEST8: emirdrp.recipes.auxiliary.mtwflat.MultiTwilightFlatRecipe
      TEST9: emirdrp.recipes.aiv.extraction.MaskSpectraExtractionRecipe
      TEST10: emirdrp.recipes.acquisition.maskcheck.MaskCheckRecipe
      TEST11: emirdrp.recipes.aiv.extraction.CSUSpectraExtractionRecipe
      TEST12: emirdrp.recipes.acquisition.bargrad.BarDetectionRecipe
      TEST13: emirdrp.recipes.acquisition.maskcheck.MaskCheckRecipe
      SPEC_SKY: emirdrp.recipes.spec.sky.SkySpecRecipe
      ARC_CALIBRATION: emirdrp.recipes.arccalibration.ArcCalibrationRecipe
      STARE_SPECTRA: emirdrp.recipes.spec.stare.StareSpectraRecipe
      LS_ABBA: emirdrp.recipes.spec.subs.BaseABBARecipe
      COMBINED_ABBA: emirdrp.recipes.spec.coadd.CoaddABBARecipe
    version: 1
products:
  - name: emirdrp.products.MasterBias
    mode: IMAGE_BIAS
    field: biasframe