name: EMIR
configurations:
  alt:
    detector:
      channels: FULL
      shape:
      - 2048
      - 2048
    keywords:
      airmass: AIRMASS
      exposure: EXPTIME
      imagetype: IMGTYP
      juliandate: MJD-OBS
    pipeline: alt
  default:
    detector:
      channels: FULL
      shape:
      - 2048
      - 2048
    keywords:
      airmass: AIRMASS
      exposure: EXPTIME
      imagetype: IMGTYP
      juliandate: MJD-OBS
    pipeline: default
modes:
- date: 2013-11-12
  description: A recipe that always fails
  key: fail
  name: Fail
  reference: numina
  status: DRAFT
  summary: A recipe that always fails
  url: http://somegtc_url.es/emir/obsmode1.html
  uuid: a7cf7b82-e527-4d53-ad7a-3dae009a1b4e
- date: 2012-05-21
  description: Recipe to process bias images
  key: IMAGE_BIAS
  name: Bias Image
  reference: IPUREMI_323
  status: DRAFT
  summary: Recipe to process bias images
  url: http://somegtc_url.es/emir/obsmode1.html
  uuid: a7ea9c0c-76a6-4609-8413-0157102ec284
- date: 2012-05-21
  description: Lines and mode lines
  key: IMAGE_DARK
  name: Dark current Image
  reference: IPUREMI_323
  status: DRAFT
  summary: Summary of Dark current Image
  url: http://somegtc_url.es/emir/obsmode4.html
  uuid: 5b15db30-7774-4823-9645-e8ca27a866af
- date: 2012-05-21
  description: Lines and mode lines
  key: IMAGE_FLAT
  name: Intensity Flat-Field
  reference: IPUREMI_323
  status: DRAFT
  summary: Summary of Intensity Flat-Field
  url: http://somegtc_url.es/emir/obsmode4.html
  uuid: bd22b260-38f9-427f-bbfd-c7767dc51e33
- date: 2012-05-21
  description: Lines and mode lines
  key: STARE_IMAGE
  name: Stare Image
  reference: IPUREMI_323
  status: DRAFT
  summary: Summary of Stare Image
  url: http://somegtc_url.es/emir/obsmode2.html
  uuid: 0325bcf1-ab5c-4946-a797-e341d8f82e0d
- date: 2012-05-21
  description: Lines and mode lines
  key: NODDED_BEAM_SWITCHED_IMAGE
  name: Nodded/Beam-switched images
  reference: IPUREMI_323
  status: DRAFT
  summary: Summary of Nodded/Beam-switched images
  url: http://somegtc_url.es/emir/obsmode3.html
  uuid: 2e9bf628-962d-4c12-b203-1a488325ac5c
- date: 2012-05-21
  description: Lines and mode lines
  key: DITHERED_IMAGE
  name: Dithered images
  reference: IPUREMI_323
  status: DRAFT
  summary: Summary of Dithered images
  url: http://somegtc_url.es/emir/obsmode4.html
  uuid: 3675a7b5-7455-492e-947a-2e607c388d1c
- date: 2012-05-21
  description: Lines and mode lines
  key: MICRODITHERED_IMAGE
  name: Micro-dithered images
  reference: IPUREMI_323
  status: DRAFT
  summary: Summary of Micro-dithered images
  url: http://somegtc_url.es/emir/obsmode4.html
  uuid: 8553b9cc-7564-469d-b230-be44051eeb90
- date: 2012-05-21
  description: Lines and mode lines
  key: MOSAICED_IMAGE
  name: Mosaiced images
  reference: IPUREMI_323
  status: DRAFT
  summary: Summary of Mosaiced images
  url: http://somegtc_url.es/emir/obsmode4.html
  uuid: ec9229d9-4c77-43a8-9dc0-77afd532e673
- date: 2012-06-12
  description: Lines and mode lines
  key: gain_mode1
  name: Gain Mode1
  reference: IPUREMI_323
  status: DRAFT
  summary: Summary of GainMode1
  url: http://somegtc_url.es/emir/obsmode4.html
  uuid: ec9229d9-4c77-43a8-9dc0-77afd532e674
- date: 2012-07-09
  description: Lines and mode lines
  key: cosmetics
  name: Cosmetics
  reference: IPUREMI_323
  status: DRAFT
  summary: Summary of GainMode1
  url: http://somegtc_url.es/emir/obsmode4.html
  uuid: 63f13bf6-b821-4c3d-9eee-32f6f924844b
- date: 2013-06-25
  description: Lines and mode lines
  key: dark_current
  name: DarkCurrent
  recipe: emirdrp.recipes.aiv.DarkCurrentRecipe
  reference: TTL 2.1.03
  status: DRAFT
  summary: Summary of DarkCurrent
  url: http://somegtc_url.es/emir/obsmode4.html
  uuid: acd1de1e-bc5f-4948-965e-d7f5b8f637b9
- date: 2014-01-14
  description: A Simple Bias recipe for testing
  key: simple_bias
  name: Simple Bias
  reference: test
  status: DRAFT
  summary: Summary of Simple Bias
  url: http://somegtc_url.es/emir/obsmode4.html
- date: 2014-03-20
  description: Does nothing
  key: TEST0
  name: Test success
  reference: test
  status: DRAFT
  summary: Summary
  url: http://somegtc_url.es/emir/obsmode4.html
  uuid: a251e55a-ab05-4109-8717-1018b6c9dbbd
- date: 2014-03-11
  description: Bias correct
  key: TEST1
  name: Test Bias Correct
  reference: test
  status: DRAFT
  summary: Summary
  url: http://somegtc_url.es/emir/obsmode4.html
  uuid: 3847286a-e39e-419b-89bd-d53555a9043c
- date: 2014-03-11
  description: Dark correct
  key: TEST2
  name: Test Dark Correct
  reference: test
  status: DRAFT
  summary: Summary
  url: http://somegtc_url.es/emir/obsmode4.html
  uuid: 4d92f7cd-3127-4fb4-a40c-758d565d9ca9 
- date: 2014-03-12
  description: Flat correct
  key: TEST3
  name: Test Flat Correct
  reference: test
  status: DRAFT
  summary: Summary
  url: http://somegtc_url.es/emir/obsmode4.html
  uuid: bd30730a-29ca-4b3c-a494-f95b4ce668b6
- date: 2014-03-12
  description: Sky subtracction
  key: TEST5
  name: Test sky subtraction
  reference: test
  status: DRAFT
  summary: Summary
  url: http://somegtc_url.es/emir/obsmode4.html
  uuid: ac94be00-92ed-43d1-94f8-0bd8a6b3deef
- date: 2014-03-12
  description: Flat correct
  key: TEST6
  name: Test pinhole extraction
  reference: test
  status: DRAFT
  summary: Summary
  url: http://somegtc_url.es/emir/obsmode4.html
  uuid: 8dfef954-d3f8-4f7f-9a5a-87609ddbfb41
- date: 2014-04-23
  description: Simple sky background
  key: IMAGE_SKY
  name: Test pinhole extraction
  reference: test
  status: DRAFT
  summary: Summary
  url: http://somegtc_url.es/emir/obsmode4.html
  uuid: 449d0f1f-2122-4cfd-8bc2-14e073ac1551
- date: 2014-12-10
  description: Slit extraction in pinhole mask
  key: TEST7
  name: Test slit extraction
  reference: test
  status: DRAFT
  summary: Summary
  url: http://somegtc_url.es/emir/obsmode4.html
  uuid: d7854cf4-0379-4e7d-9b1f-e045784ce90e
- key: TEST8
  name: Multiflat
  summary: Multiflat
  description: Simultaneous flat in several bands
- date: 2015-04-24
  description: Wavelength calibration from arc
  key: ARC_CALIBRATION
  name: Wavelength calibration
  reference: test
  status: DRAFT
  url: http://somegtc_url.es/emir/obsmode4.html
  uuid: F8AE2344-A242-4695-AFD9-DB5EDCBF0DD6
- date: 2015-05-07
  description: Extracts spectra of the slits in the AIV mask
  key: TEST9
  name: Slit-mask spectra extraction 
  reference: test
  status: DRAFT
  summary: Summary
  url: http://somegtc_url.es/emir/obsmode4.html
  uuid: 40f353e8-42ae-4187-9487-0fd81531d774
- date: 2015-05-21
  description: Extracts spectra of the slits in the AIV mask
  key: TEST9
  name: Slit-mask spectra extraction
  reference: test
  status: DRAFT
  summary: Summary
  url: http://somegtc_url.es/emir/obsmode4.html
  uuid: 40f353e8-42ae-4187-9487-0fd81531d774
- date: 2015-11-03
  description: Positions of the CSU bars
  key: TEST10
  name: Bar detection
  summary: Positions of the CSU bars
- date: 2015-11-12
  description: Extraction of spectra
  key: TEST11
  name: TEST11
  summary: Extraction of spectra
- date: 2015-11-25
  description: Alternative positions of the CSU bars
  key: TEST12
  name: TEST12
  summary: Positions of CSU bars
- date: 2012-05-21
  description: Lines and mode lines
  key: FULL_DITHERED_IMAGE
  name: Dithered images
  reference: IPUREMI_323
  status: DRAFT
  summary: Summary of Dithered images
  url: http://somegtc_url.es/emir/obsmode4.html
- key: LS_ABBA
  name: Long Slit ABBA
  summary: Spectroscopy ABBA
  description: Spectroscopy ABBA
- key: COMBINE_ABBA
  name: Combine individual Long Slit ABBA
  summary: Combine individual Long Slit ABBA
  description: Combine individual Long Slit ABBA
pipelines:
  default:
    recipes:
      IMAGE_BIAS: emirdrp.recipes.auxiliary.BiasRecipe
      IMAGE_DARK: emirdrp.recipes.auxiliary.DarkRecipe
      IMAGE_FLAT: emirdrp.recipes.auxiliary.IntensityFlatRecipe
      IMAGE_SKY: emirdrp.recipes.auxiliary.DitherSkyRecipe
      DITHERED_IMAGE: emirdrp.recipes.image.join.JoinDitheredImagesRecipe
      FULL_DITHERED_IMAGE: emirdrp.recipes.image.dither.DitheredImageRecipe
      MICRODITHERED_IMAGE: emirdrp.recipes.image.micro.MicroditheredImageRecipe
      MOSAICED_IMAGE: emirdrp.recipes.image.mosaic.MosaicRecipe
      NODDED_BEAM_SWITCHED_IMAGE: emirdrp.recipes.image.nodded.NBImageRecipe
      STARE_IMAGE: emirdrp.recipes.image.stare.StareImageBaseRecipe
      fail: numina.core.utils.AlwaysFailRecipe
      gain_mode1: emirdrp.recipes.engineering.GainRecipe1
      cosmetics: emirdrp.recipes.engineering.CosmeticsRecipe
      simple_bias: emirdrp.recipes.aiv.SimpleBiasRecipe
      TEST0: numina.core.utils.AlwaysSuccessRecipe
      TEST1: emirdrp.recipes.aiv.TestBiasCorrectRecipe
      TEST2: emirdrp.recipes.aiv.TestDarkCorrectRecipe
      TEST3: emirdrp.recipes.aiv.TestFlatCorrectRecipe
      TEST4: emirdrp.recipes.aiv.TestFlatCorrectRecipe
      TEST5: emirdrp.recipes.aiv.sky.TestSkyCorrectRecipe
      TEST6: emirdrp.recipes.aiv.pointsources.TestPointSourceRecipe
      TEST7: emirdrp.recipes.aiv.slits.TestSlitDetectionRecipe
      TEST8: emirdrp.recipes.auxiliary.mtwflat.MultiTwilightFlatRecipe
      TEST9: emirdrp.recipes.aiv.extraction.MaskSpectraExtractionRecipe
      TEST10: emirdrp.recipes.aiv.bargrad.BarDetectionRecipe
      TEST11: emirdrp.recipes.aiv.extraction.CSUSpectraExtractionRecipe
      TEST12: emirdrp.recipes.aiv.bargrad.BarDetectionRecipe
      TEST13: emirdrp.recipes.acquisition.maskcheck.MaskCheckRecipe
      ARC_CALIBRATION: emirdrp.recipes.arccalibration.ArcCalibrationRecipe
      LS_ABBA: emirdrp.recipes.spec.subs.BaseABBARecipe
      COMBINE_ABBA: emirdrp.recipes.spec.coadd.CoaddABBARecipe
    version: 1
