name: EMIR
configurations:
  values:
  - 225fcaf2-7f6f-49cc-972a-70fd0aee8e96
datamodel: emirdrp.datamodel.EmirDataModel
modes:
- description: A recipe that always fails
  key: fail
  name: Fail
  summary: A recipe that always fails
- description: Recipe to process bias images
  key: IMAGE_BIAS
  name: Bias Image
  summary: Recipe to process bias images
- description: Lines and mode lines
  key: IMAGE_DARK
  name: Dark current Image
  summary: Summary of Dark current Image
- description: Lines and mode lines
  key: IMAGE_FLAT
  name: Intensity Flat-Field
  summary: Summary of Intensity Flat-Field
- description: Lines and mode lines
  key: STARE_IMAGE
  name: Stare Image
  summary: Summary of Stare Image
- description: Lines and mode lines
  key: NODDED_BEAM_SWITCHED_IMAGE
  name: Nodded/Beam-switched images
  summary: Summary of Nodded/Beam-switched images
- description: Lines and mode lines
  key: DITHERED_IMAGE
  name: Dithered images
  summary: Summary of Dithered images
- description: Lines and mode lines
  key: MICRODITHERED_IMAGE
  name: Micro-dithered images
  summary: Summary of Micro-dithered images
- description: Lines and mode lines
  key: gain_mode1
  name: Gain Mode1
  summary: Summary of GainMode1
- description: Lines and mode lines
  key: cosmetics
  name: Cosmetics
  summary: Summary of GainMode1
- description: Lines and mode lines
  key: dark_current
  name: DarkCurrent
  recipe: emirdrp.recipes.aiv.DarkCurrentRecipe
  summary: Summary of DarkCurrent
- description: A Simple Bias recipe for testing
  key: simple_bias
  name: Simple Bias
  summary: Summary of Simple Bias
- description: Does nothing
  key: FRAME
  name: Test success
  summary: Summary
- description: Bias correct
  key: TEST1
  name: Test Bias Correct
  summary: Summary
- description: Dark correct
  key: TEST2
  name: Test Dark Correct
  summary: Summary
- description: Flat correct
  key: TEST3
  name: Test Flat Correct
  summary: Summary
- description: Sky subtracction
  key: SKY_CORRECT
  name: Test sky subtraction
  summary: Summary
- description: Flat correct
  key: POINT_SOURCE
  name: Test pinhole extraction
  summary: Summary
- description: Simple sky background
  key: IMAGE_SKY
  name: Test pinhole extraction
  summary: Summary
- description: Slit extraction in pinhole mask
  key: TEST7
  name: Test slit extraction
  summary: Summary
- description: Simultaneous flat in several bands
  key: FLAT
  name: Multiflat
  summary: Multiflat
- description: Wavelength calibration from arc
  key: ARC_CALIBRATION
  name: Wavelength calibration from arc
  summary: Wavelength calibration from arc
- description: Extracts spectra of the slits in the AIV mask
  key: TEST9
  name: Slit-mask spectra extraction
  summary: Summary
- description: Extracts spectra of the slits in the AIV mask
  key: TEST9
  name: Slit-mask spectra extraction
  summary: Summary
- description: Positions of the CSU bars
  key: TEST10
  name: Bar detection
  summary: Positions of the CSU bars
- description: Extraction of spectra
  key: TEST11
  name: TEST11
  summary: MOS mask check
- description: Checks the positions of reference stars in MOS mask
  key: BAR_POS
  name: BAR_POS
  summary: Positions of CSU bars
- key: TEST13
  name: TEST13
  summary: Mask Check
  description: Acquire and check mask
- description: Lines and mode lines
  key: FULL_DITHERED_IMAGE
  name: Dithered images
  summary: Summary of Dithered images
- key: STARE_SPECTRA
  name: Stare Spectra
  summary: Stare Spectra
  description: Stare Spectra
- key: STARE_SPECTRA_WAVE
  name: Stare Spectra with Wavelength Calibration
  summary: Stare Spectra with Wavelength Calibration
  description: Stare Spectra with Wavelength Calibration
- key: GENERATE_RECTWV_COEFF
  name: Generate rectwv calibration coefficients
  summary: Generate rectwv calibration coefficients
  description: Generate rectwv calibration coefficients
- key: STARE_SPECTRA_RECTWV
  name: Stare Spectra with Precomputed Wavelength Calibration
  summary: Stare Spectra with Precomputed Wavelength Calibration
  description: Stare Spectra with Precomputed Wavelength Calibration
- key: ABBA_SPECTRA_RECTWV
  name: ABBA Spectra with Precomputed Wavelength Calibration
  summary: ABBA Spectra with Precomputed Wavelength Calibration
  description: ABBA Spectra with Precomputed Wavelength Calibration
- key: ABBA_SPECTRA_FAST_RECTWV
  name: ABBA Spectra with Precomputed Wavelength Calibration (fast)
  summary: ABBA Spectra with Precomputed Wavelength Calibration (fast)
  description: ABBA Spectra with Precomputed Wavelength Calibration (fast)
- key: SPEC_FLAT_LOWFREQ
  name: Low-frequency spectroscopic flatfield
  summary: Low-frequency spectroscopic flatfield
  description: Low-frequency spectroscopic flatfield
- key: SPEC_FLAT_PIX2PIX
  name: Pixel-to-pixel spectroscopic flatfield
  summary: Pixel-to-pixel spectroscopic flatfield
  description: Pixel-to-pixel spectroscopic flatfield
- key: LS_ABBA
  name: Long Slit ABBA
  summary: Spectroscopy ABBA
  description: Spectroscopy ABBA
- key: COMBINED_ABBA
  name: Combined individual Long Slit ABBA
  summary: Combined individual Long Slit ABBA
  description: Combined individual Long Slit ABBA
- key: SPEC_SKY
  name: SPEC_SKY
  summary: SPEC_SKY
  description: SPEC_SKY
- key: SPECTRAL_FLAT
  name: SPECTRAL FLAT mode
  summary: SPECTRAL FLAT mode
  description: SPECTRAL FLAT mode
- key: LOAD_RECWAVE
  name: Load MasterRecWave
  summary: load a MasterRecWave structure from file
- key: LOAD_SKYLINES
  name: Load SkyLinesCatalog
  summary: load a SkyLinesCatalog structure from file
- key: IMG_ACQ
  name: Mask Acquisition
  summary: Finds objects for mask acquisition
- key: FINE_CENTERING
  name: MOS fine centering
  summary: Finds the best position of the slits
- key: BASIC_COMBINE
  name: Combine
  summary: Combine
pipelines:
  default:
    products:
      MasterBias: emirdrp.products.MasterBias
      MasterBadPixelMask: emirdrp.products.MasterBadPixelMask
      MasterDark: emirdrp.products.MasterDark
      MasterIntensityFlat: emirdrp.products.MasterIntensityFlat
      MasterSpectralFlat: emirdrp.products.MasterSpectralFlat
      SkyLinesCatalog: emirdrp.products.SkyLinesCatalog
    provides:
      - name: MasterBadPixelMask
        mode: cosmetics
        field: maskframe
      - name: MasterBias
        mode: IMAGE_BIAS
        field: biasframe
      - name: MasterDark
        mode: IMAGE_DARK
        field: darkframe
      - name: MasterIntensityFlat
        mode: IMAGE_FLAT
        field: flatframe
      - name: MasterSpectralFlat
        mode: SPECTRAL_FLAT
        field: flatframe
      - name: MasterSky
        mode: IMAGE_SKY
        field: skyframe
      - name: SkySpectrum
        mode: SPEC_SKY
        field: skyspec
      - name: MasterRectWave
        mode: LOAD_RECWAVE
        field: master_rectwv
      - name: SkyLinesCatalog
        mode: LOAD_SKYLINES
        field: skylines
    recipes:
      BASIC_COMBINE: numina.core.utils.Combine
      IMAGE_BIAS: emirdrp.recipes.auxiliary.BiasRecipe
      IMAGE_DARK: emirdrp.recipes.auxiliary.DarkRecipe
      IMAGE_FLAT: emirdrp.recipes.auxiliary.IntensityFlatRecipe2
      IMAGE_SKY: emirdrp.recipes.auxiliary.DitherSkyRecipe
      SPECTRAL_FLAT: emirdrp.recipes.auxiliary.SpectralFlatRecipe
      DITHERED_IMAGE: emirdrp.recipes.image.join.JoinDitheredImagesRecipe
      FULL_DITHERED_IMAGE: emirdrp.recipes.image.dither.FullDitheredImagesRecipe
      MICRODITHERED_IMAGE: emirdrp.recipes.image.micro.MicroditheredImageRecipe
      NODDED_BEAM_SWITCHED_IMAGE: emirdrp.recipes.image.nodded.NBImageRecipe
      STARE_IMAGE: emirdrp.recipes.image.stare.StareImageRecipe2
      fail: numina.core.utils.AlwaysFailRecipe
      gain_mode1: emirdrp.recipes.engineering.detectorgain.GainRecipe1
      cosmetics: emirdrp.recipes.engineering.cosmetics.CosmeticsRecipe
      simple_bias: emirdrp.recipes.aiv.SimpleBiasRecipe
      FRAME: numina.core.utils.AlwaysSuccessRecipe
      TEST1: emirdrp.recipes.aiv.TestBiasCorrectRecipe
      TEST2: emirdrp.recipes.aiv.TestDarkCorrectRecipe
      TEST3: emirdrp.recipes.aiv.TestFlatCorrectRecipe
      TEST4: emirdrp.recipes.aiv.TestFlatCorrectRecipe
      SKY_CORRECT: emirdrp.recipes.aiv.sky.TestSkyCorrectRecipe
      POINT_SOURCE: emirdrp.recipes.aiv.pointsources.TestPointSourceRecipe
      TEST7: emirdrp.recipes.aiv.slits.TestSlitDetectionRecipe
      FLAT: emirdrp.recipes.auxiliary.mtwflat.MultiTwilightFlatRecipe
      TEST9: emirdrp.recipes.acquisition.maskcheck.MaskCheckRecipe
      TEST10: emirdrp.recipes.acquisition.maskcheck.MaskCheckRecipe
      TEST11: emirdrp.recipes.acquisition.maskcheck.MaskCheckRecipe
      BAR_POS: emirdrp.recipes.acquisition.bargrad.BarDetectionRecipe
      TEST13: emirdrp.recipes.acquisition.maskcheck.MaskCheckRecipe
      IMG_ACQ: emirdrp.recipes.acquisition.maskcheck.MaskCheckRecipe
      FINE_CENTERING: emirdrp.recipes.acquisition.centering.FineCenteringRecipe
      SPEC_SKY: emirdrp.recipes.spec.sky.SkySpecRecipe
      ARC_CALIBRATION: emirdrp.recipes.calibration.arc.ArcCalibrationRecipe
      STARE_SPECTRA: emirdrp.recipes.spec.stare.StareSpectraWaveRecipe
      STARE_SPECTRA_WAVE: emirdrp.recipes.spec.stare.StareSpectraWaveRecipe
      GENERATE_RECTWV_COEFF: emirdrp.recipes.spec.stare.GenerateRectwvCoeff
      STARE_SPECTRA_RECTWV: emirdrp.recipes.spec.stare.StareSpectraRectwv
      ABBA_SPECTRA_RECTWV: emirdrp.recipes.spec.abba.ABBASpectraRectwv
      ABBA_SPECTRA_FAST_RECTWV: emirdrp.recipes.spec.abba.ABBASpectraFastRectwv
      SPEC_FLAT_LOWFREQ: emirdrp.recipes.spec.flatlowfreq.SpecFlatLowFreq
      SPEC_FLAT_PIX2PIX: emirdrp.recipes.spec.flatpix2pix.SpecFlatPix2Pix
      LS_ABBA: emirdrp.recipes.spec.subs.BaseABBARecipe
      COMBINED_ABBA: emirdrp.recipes.spec.coadd.CoaddABBARecipe
      LOAD_RECWAVE: emirdrp.recipes.auxiliary.load.RecWaveRecipe
    version: 1
